### ISSUE TITLE
Composer autoload

### ISSUE THREAD

**Issue by RobertBoes** [chargebee/chargebee-php#11]
Since #4 is already open for more than a year, I decided to open a new issue with more or less the same problem.
When using the Chargebee autoload with Laravel (composer), all files are being loaded because [Chargebee.php](https://github.com/chargebee/chargebee-php/blob/master/lib/ChargeBee.php) requires every single class used in this project.

**Comment by dolcy** [comment]
+1
This entire library needs a revamp in fact.

**Comment by ashleydw** [comment]
+1 for the total revamp. Code is very out of date - simple things like being unable to get an array of values as in https://github.com/chargebee/chargebee-php/issues/9 is needed

**Comment by juanstiza** [comment]
+1 for the revamp.

**Comment by PowerJESUS** [comment]
Totally agree.

**Comment by icetee** [comment]
Man.. please use namespaces

**Comment by frankarensmeier** [comment]
This is still an issue after more than 4 years. This is a great pain point for us right now.

**Comment by icetee** [comment]
> This is still an issue after more than 4 years. This is a great pain point for us right now.

Try use my fork: https://github.com/chargebee/chargebee-php/pull/23

**Comment by frankarensmeier** [comment]
@icetee Thank you for for the link - looks very good. Any idea if / when this can be merged into master? This is becoming more and more annoying. I did some profiling on the Chargebee code base with and without proper PSR-0 autoloading and the difference is quite significant. On my local docker container, Chargebee stands for 25% of total execution time whenever a page gets rendered. All files are loaded no matter what (only a small fraction of all pages actually use CB). This is not good!

**Comment by cb-rakesh** [comment]
This has been fixed in v3.0.0
