### ISSUE TITLE
[Suggestion] Add a __toString() method to ChargeBee_Model to support attempts saving it as a string

### ISSUE THREAD

**Issue by claw68** [chargebee/chargebee-php#15]
On ChargeBee_Model class

`public function __toString()
{
    return json_encode($this->_values);
}`

**Comment by claw68** [comment]
#16

**Comment by jkindness** [comment]
Thanks for this. A simple return $this->_values function has been needed for so long. Anyone using this as part of their restAPI would largely benefit from this. Please consider adding it to the master version.

**Comment by SangeethaBaskaran** [comment]
Hi,
The method 'toJson()' has been added to master version.
