### ISSUE TITLE
Improved attribute name consistency and documentation

### ISSUE THREAD

**Issue by brianmuse** [chargebee/chargebee-php#18]
I noticed some confusing inconsistencies with some of the models.

`Invoice::$allowed` uses camel casing for attributes.
`LineItem::$allowed` however, uses snake case with underscores.

It'd be easier to work with these objects if there was a common style. 

On a second related note, it would be _hugely_ beneficial when working with these classes if the properties were documented using PHPDoc in a way that most IDEs support.

For example:

```
/**
 * @property string $id
 * @property string $subscription_id
 * @property int $date_from
 * ...
 */
class ChargeBee_InvoiceLineItem extends ChargeBee_Model
{
```

**Comment by cb-rakesh** [comment]
This has been fixed in v3.0.0
