### ISSUE TITLE
create_function is deprecated in php 7.2

### ISSUE THREAD

**Issue by seedprod** [chargebee/chargebee-php#20]
You have to utilities function that use this: 
toCamelCaseFromUnderscore
toUnderscoreFromCamelCase

**Comment by eric-famiglietti** [comment]
I am also having this issue. Unfortunately, if the issue can't be resolved we may need to switch to another vendor!

**Comment by saravana-cb** [comment]
We have the fix.  We will roll it out in two or three days.

**Comment by SangeethaBaskaran** [comment]
PR #21 has been merged to fix the issue.

**Comment by TomasVotruba** [comment]
If you ever need to upgrade more  `create_function` cases, [Rector does it pretty well](https://github.com/rectorphp/rector/commit/3376254f7742abab3fde0a865ae4de8a420e964f).
