### ISSUE TITLE
Php Version Issue

### ISSUE THREAD

**Issue by zachgarcia1** [chargebee/chargebee-php#25]
Getting an error of

`Use of undefined constant s - assumed 's' (this will throw an Error in a future version of PHP)`

From

`chargebee/chargebee-php/lib/ChargeBee/Curl.php`

seems to be coming from line 41 which is

`array_push($httpHeaders, 'Accept: application/json', "User-Agent: " . $userAgent , "Lang-Version: " . phpversion() , "OS-Version: " . php_uname(s). " " . php_uname(m) . " " . php_uname(r)); // Adding headers to array`

My current version of php is 7.3
![screen shot 2019-03-08 at 8 16 10 am](https://user-images.githubusercontent.com/12938920/54037061-779b6900-417a-11e9-9516-fc824c6b4f9c.png)

**Comment by zachgarcia1** [comment]
https://github.com/chargebee/chargebee-php/commit/4a85ddff5eec3fc82ee5c9e1d1133658a1209efc#diff-aeb4637f48ebc9843f1a666c84ad782d

Seems to have been affected by this commit.

**Comment by cb-goutham** [comment]
@zachgarcia1 
We will fix this ASAP . Please use the previous php version 2.6.0 until then .
Thanks.

**Comment by zachgarcia1** [comment]
confirmed working on 2.6.0 will set composer file to reflect changes and will check back for the update. Thank you for your quick response.

**Comment by gitomato** [comment]
Thanks for quickly publishing a fixed 2.6.2 version.
However, it's not available on Packagist yet. Could you publish it?
https://packagist.org/packages/chargebee/chargebee-php

**Comment by SangeethaBaskaran** [comment]
@gitomato Published in Packagist. Thanks.

**Comment by zachgarcia1** [comment]
thank you for the update. confirmed working on latest version.
