### ISSUE TITLE
Class loader is not able to load all models

### ISSUE THREAD

**Issue by mariendev** [chargebee/chargebee-php#29]
Our account has hierarchy enabled. But when I try to load a customer with a hierarchy it fails because the class is not loaded.

Error messages:
Error: Class 'ChargeBee_CustomerParentAccountAccess' not found
Error: Class 'ChargeBee_CustomerChildAccountAccess' not found

**Comment by s-andronnikov** [comment]
Try this fork https://github.com/s-andronnikov/chargebee-php
It has namespaces

**Comment by cb-rakesh** [comment]
This has been fixed in v3.0.0
