### ISSUE TITLE
Require Product Family and other upcoming features

### ISSUE THREAD

**Issue by keremcankaya0** [chargebee/chargebee-php#30]
Hey guys, 

Thanks for the quality work. 

I've started using Product Family feature as a beta user. 

Required classes are present in the Models folder however they're not "required" in ChargeBee.php file. 

In order to test out these features I needed to modify the files and remove ChargeBee from composer.

I can make a PR if you guys need help so that I can use ChargeBee as a composer package.

**Comment by RCade** [comment]
@keremcankaya0 If it is `ItemFamily` I have included it in a PR a made yesterday to fix other missing requires.  I do not see a class for Product Family.

**Comment by keremcankaya0** [comment]
Hey @RCade, it is ItemFamily. I've checked your PR and seems like you've covered the required classes.
Thanks, when do you thing you guys will merge with master and available on composer?

**Comment by cb-goutham** [comment]
This has been fixed in [2.8.2](https://github.com/chargebee/chargebee-php/releases/tag/v2.8.2)
