### ISSUE TITLE
v3.1.0 requires guzzlehttp/guzzle ^6.5

### ISSUE THREAD

**Issue by fsjdg** [chargebee/chargebee-php#36]
Previous versions as 2.8.2 ( which is what i have installed right now ) is working fine with guzzlehttp/guzzle ^7.0 ( which is what i have installed right now ). Newest version (3.1.0) requires guzzlehttp/guzzle ^6.5 to be installed. Is there a way to handle this? Can you increase the minimum guzzlehttp/guzzle version?

**Comment by cb-yateshmathuria** [comment]
We have released stable version [v3.2.0](https://github.com/chargebee/chargebee-php/tree/v3.2.0)
