### ISSUE TITLE
Implement namespaces

### ISSUE THREAD

**Issue by academo** [chargebee/chargebee-php#4]
Would be nice if you could implement namespaces in the whole library

**Comment by SInCE** [comment]
:+1: for namespaces

**Comment by hypnotisttom** [comment]
Absolutely!  I run into so many issues without having namespaces in this project.  I can't believe it doesn't have namespaces nearly 5 years later...  I see the PR out there, so I hope this gets resolved soon.

**Comment by s-andronnikov** [comment]
Try this fork https://github.com/s-andronnikov/chargebee-php
It has namespaces
