### ISSUE TITLE
Typo in init.php

### ISSUE THREAD

**Issue by rjnl** [chargebee/chargebee-php#42]
Noticed this when testing on Linux. Working fine on Windows.

In `lib/init.php`, line 193, "content.php" should be "Content.php".

Change line 193 from:
`require(dirname(__FILE__) . '/ChargeBee/Models/content.php');`

to 

`require(dirname(__FILE__) . '/ChargeBee/Models/Content.php');`

**Comment by cb-khushbubibay** [comment]
Hi @rjnl 
This issue has been fixed in v3.5.2.
