### ISSUE TITLE
No way to retrieve the 'retry-after' header in case of 429 OperationFailedException 

### ISSUE THREAD

**Issue by yched** [chargebee/chargebee-php#52]
From the ["Error handling" section of the API docs](https://apidocs.eu.chargebee.com/docs/api/error-handling?prod_cat_ver=2&lang=php#error_handling) : 

> If you receive an HTTP 429 Too Many Requests error response to an API call, it means that the API requests for your Chargebee site have exceeded acceptable limits. Chargebee may also send a [Retry-After](https://tools.ietf.org/html/rfc7231#section-7.1.3) header indicating the time duration to wait before sending a new request. 

But on a HTTP 429 error, trhe Chargebee-php library throws an OperationFailedException, and offers no way to access the response headers, and thus no way to read the "Retry-After" value sent by Chargbee API.

**Comment by cb-alish** [comment]
Hi @yched, sorry for the delay in response. This has been fixed on the latest release, v3.28.0. You'll be able to access headers in the following manner. Please give it a try and let us know if you face any issues. 

```php
catch (APIError $e) {
        $errorHeaders = $e->getHeaders();
        $retryAfterHeaders = $errorHeaders['Retry-After'][0];
        echo $retryAfterHeaders . "\n";
}

```

**Comment by yched** [comment]
Tnanjs @cb-alish , this works great ! :+1:

**Comment by cb-sriramthiagarajan** [comment]
Thanks for the confirmation @yched 👍
