### ISSUE TITLE
Is is Chargebee or ChargeBee?

### ISSUE THREAD

**Issue by soulseekah** [chargebee/chargebee-php#56]
### Description of the Bug

We're having a hard time understanding whether there's a mistake in the classnames and namespaces. Is it Chargebee or ChargeBee?

### Steps to reproduce

Open a class.
See ChargeBee.

### Expected Behavior

See Chargebee throughout the naming.

### Operating System

Linux

### Language version

PHP 8.3

### Library version

latest

**Comment by cb-alish** [comment]
Hi @soulseekah sorry for the confusion, it is actually ChargeBee. We can use our classes in the following way.
