### ISSUE TITLE
Tiered subscription example

### ISSUE THREAD

**Issue by temi3500** [chargebee/chargebee-php#62]
### What problem does your feature request address?

Can you please provide an example of tiered subscriptions work 
` 
           $units=(int)$request->units;
            
           $subscriptionData = [
            'subscription_items[item_price_id][0]' => $request->item_price_id,
        
            // First tier
            'item_tiers[item_price_id][0]' => $request->item_price_id,
            'item_tiers[starting_unit][0]' => 1,
            'item_tiers[ending_unit][0]' => $units,
            'item_tiers[price_in_decimal][0]' => number_format($request->calculated_price / $request->units, 2, '.', ''), // Unit price for first tier
        
            // Second tier (if applicable)
            'item_tiers[item_price_id][1]' => $request->item_price_id,
            'item_tiers[starting_unit][1]' => $units + 1,
            'item_tiers[ending_unit][1]' => null,
            'item_tiers[price_in_decimal][1]' => number_format($request->calculated_price / $request->units, 2, '.', ''), // Same unit price for second tier
        ];`
        
        
        the above code is not working for me and i really need a example to create a susbscription based on tiered

**Comment by cb-alish** [comment]
Hi @temi3500, it looks like the quantity is missing from your example. Here's how you can use a tiered subscription.

1. Scenario one: Create a tiered subscription without overriding the default item price, using the same tier configuration as the item price.
```php 
function createSubscriptionForItems()
{
        Subscription::createWithItems("BTTwbPUSZsFvomjs", array(
            "subscriptionItems" => array(
                array(
                    "itemPriceId" => "{tiered-itemPrice-id}",
                    "quantity" => 11,
                )
            )
        ));
}
```
2. Scenario two: Override the tier details and use custom prices.
```php 
function createSubscriptionForItems()
{

    Subscription::createWithItems("BTTwbPUSZsFvomjs", array(
        "subscriptionItems" => array(
            array(
                "itemPriceId" => {tiered-itemPrice-id},
                "quantity" => 11,
            )
        ),
        "itemTiers" => array(
            array(
                "itemPriceId" => {tiered-itemPrice-id}, // first tier
                "startingUnit" => 1,
                "endingUnit" => 10,
                "price" => 150,
            ),
            array(
                "itemPriceId" => {tiered-itemPrice-id}, // second tier
                "startingUnit" => 11,
                "price" => 150,
            )
        )
    ));
}
```
Please Note: To enable tier range overrides at the API level, contact the [ChargeBee support](https://support.chargebee.com/support/) team to activate `ALLOW_TIER_RANGE_OVERRIDE` for your site.

**Comment by cb-alish** [comment]
Hi @Temi3500, could you confirm if the example worked for you?
