### ISSUE TITLE
get() method to get serializable values from ChargeBee_Model

### ISSUE THREAD

**Issue by yemkay** [chargebee/chargebee-php#9]
Can we add a function in ChargeBee_Model to get array values? It will be useful to serialize them in DB and restore them back later.

```
class ChargeBee_Model
{
  ...
  function getValues()
  {
    return $this->_values;
  }
}
```

**Comment by SangeethaBaskaran** [comment]
Hi, 
The method getValues() to get array values is now added to ChargeBee_Model.
